from .home import *
from .login import *
from .dashboard_aluno import *
from .dashboard_avaliador import *
from .trabalho import *
from .auth import *
from .dashboard_admin import *
from .admin import *
from .avaliacao import *
from .criar_trabalho import *
from .certificado import *
from .exportar import *